spring:
  application:
    name: resident-service
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/resident-service
  jpa:
    hibernate:
      ddl-auto: create-drop
